=== emina2222/PripremaIST/adresar.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT adresar (osoba)+>
<!ELEMENT osoba (punoIme,datumRodjenja,adresa,(email)+)>
<!ELEMENT punoIme (ime,(srednjeIme)?,(prezime)+)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT srednjeIme (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT datumRodjenja (dan,mesec,godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ATTLIST adresa status (privremena|stalna) "privremena">
<!ELEMENT email (#PCDATA)>
<!ATTLIST email status (privatni|sluzbeni) #REQUIRED>

=== emina2222/PripremaIST/adresar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE adresar SYSTEM "adresar.dtd">

<adresar>
  <osoba>
    <punoIme>
      <ime>Emina</ime>
      <srednjeIme>Elizabeta</srednjeIme>
      <prezime>Marmarac</prezime>
    </punoIme>
    <datumRodjenja>
      <dan>2</dan>
      <mesec>2</mesec>
      <godina>1999</godina>
    </datumRodjenja>
    <adresa status="stalna">
      Sumadijske divizije 6, Beograd
    </adresa>
    <email status="privatni">emina.emax@gmail.com</email>
  </osoba>
</adresar>
